### ISSUE TITLE
The repo looks emtpy; how to access the data or analysis 

### ISSUE THREAD

**Issue by thammegowda** [nitikam/tangled#1]
Hi,

I am unable to find any content besides a single line in README.  (latest commit: https://github.com/nitikam/tangled/commit/b6725cf11ec0697114635cca732b72e95819b161 )
Could you please inform me how to access the code, data or any analysis 

Thanks,

**Comment by nitikam** [comment]
I've uploaded the code and data to reproduce results for correlations without outliers. I'm sorry for the delay.

**Comment by thammegowda** [comment]
thanks.
